
name: exercicio 1


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

   workflow_dispatch:

jobs:
  jobs1: 
    name: Primeiro job
    runs-on: ubuntu-laster
    
     steps:
      - name: Passo 1
        run: env | sort
        
   jobs2:
    name: Segundo job
    runs-on: windows-latest
   
    steps:
      - name: Passo 2
        run: env | sort
        
   jobs3:
     name: Terceiro job
     runs-on: marcos-latest
     
      steps:
      - name: Passo 3
        run: env | sort
     
   jobs4:
     name: Quarto job
     runs-on: windows-latest
     needs: [job1, job2, job3]
   
    steps:
      - name: Passo 4
        run: env | sort
    
  
